### ISSUE TITLE
Library not loaded: Combine.framework

### ISSUE THREAD

**Issue by hrvstr** [Impedimenta/Suitcase#5]
After installing Suitcase and trying to run one of the demo apps I get this output:

````
dyld: Library not loaded: /System/Library/Frameworks/Combine.framework/Versions/A/Combine
  Referenced from: /usr/local/bin/Suitcase
  Reason: image not found
[1]    11407 abort      Suitcase
````

Do I need Xcode to use this tool?

macOS Mojave 10.14.6 18G4032
Xcode command line tools installed.

**Comment by rjstelling** [comment]
Thanks for the feedback.

What version of macOS are you running? 

I will investigate this, I didn't think Xcode was required but Catalina is.

**Comment by hrvstr** [comment]
Ha, I was just adding my system info but you already replied. I am still using Mojave so that's the problem.

macOS Mojave 10.14.6 18G4032

**Comment by rjstelling** [comment]
Thanks for the update... I will make it more explicit in the read me.

**Comment by royaso** [comment]
so does that means Mojave could not install it?

**Comment by rjstelling** [comment]
@royaso Unfortunately not. Catalina is getting better with every point release.
